export const dummyItems = [
  {
    id: 1,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/apples.jpg",
  },
  {
    id: 2,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/bread.jpg",
  },
  {
    id: 3,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/chicken-soup.jpg",
  },
  {
    id: 4,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/pork.jpg",
  },
  {
    id: 5,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/tofu.jpg",
  },
  {
    id: 6,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/apples.jpg",
  },
  {
    id: 7,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/bread.jpg",
  },
  {
    id: 8,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/chicken-soup.jpg",
  },
  {
    id: 9,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/pork.jpg",
  },
  {
    id: 10,
    title: "안녕하세요",
    likes: 10,
    date: "어머니가 해주신 짬뽕이에요",
    member_id: 1,
    member_nickname: "기타치는이현태",
    comment_count: 5,
    image_url: "/img/tofu.jpg",
  },
];
